CREATE SCHEMA IF NOT EXISTS `EventosDB`;

CREATE TABLE IF NOT EXISTS `EventosDB`.`Users` (
	UserId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Username NVARCHAR(25) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Created DATETIME NOT NULL,
	Updated DATETIME NULL
);

CREATE TABLE IF NOT EXISTS `EventosDB`.`Eventos` (
	EventoId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Titulo NVARCHAR(255) NOT NULL,
	Descripcion TEXT NOT NULL,
	Lugar NVARCHAR(255) NOT NULL,
	Destacado BOOL NOT NULL,
    Imagen TEXT NULL,
	Created DATETIME NOT NULL,
	Updated DATETIME NULL
);

CREATE TABLE IF NOT EXISTS `EventosDB`.`EventosFechas` (
	EventoFechaId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EventoId INT(11) NOT NULL,
    Inicio DATETIME NOT NULL,
    Fin DATETIME NOT NULL,
    Precio NUMERIC NULL,
    Created DATETIME NOT NULL,
	Updated DATETIME NULL
);

ALTER TABLE `EventosDB`.`EventosFechas`
ADD CONSTRAINT FK_Eventos_EventosFechas_EventoId FOREIGN KEY(EventoId) REFERENCES `EventosDB`.`Eventos`(EventoId);

#Creacion de usuario
INSERT INTO `EventosDB`.`Users`
VALUES(DEFAULT, 'test', '$2b$10$lhizqGxAMI0Ki8sOld8.3uB8bYst/LCSUQK0Y57GTvjq1EEzxLrye', '2021-08-03 02:07:56', NULL);
